library(shinytest2)

test_that("{shinytest2} recording: funcplots", {
  app <- AppDriver$new(test_path("../.."), variant = platform_variant(), name = "funcplots", 
      height = 551, width = 979)
  app$click("go")
  app$expect_screenshot()
  app$set_inputs(expr = "")
  app$set_inputs(expr = "\\")
  app$set_inputs(expr = "\\f")
  app$set_inputs(expr = "\\fra")
  app$set_inputs(expr = "\\frac")
  app$set_inputs(expr = "\\frac{")
  app$set_inputs(expr = "\\frac{x")
  app$set_inputs(expr = "\\frac{x + ")
  app$set_inputs(expr = "\\frac{x +  ")
  app$set_inputs(expr = "\\frac{x + 2 ")
  app$set_inputs(expr = "\\frac{x + 2} ")
  app$set_inputs(expr = "\\frac{x + 2}{ ")
  app$set_inputs(expr = "\\frac{x + 2}{x ")
  app$set_inputs(expr = "\\frac{x + 2}{x^ ")
  app$set_inputs(expr = "\\frac{x + 2}{x^2 ")
  app$set_inputs(expr = "\\frac{x + 2}{x^2 -  ")
  app$set_inputs(expr = "\\frac{x + 2}{x^2 - 1 ")
  app$set_inputs(expr = "\\frac{x + 2}{x^2 - 1} ")
  app$expect_values()
  app$click("go")
  app$expect_screenshot()
})
