library(shinytest2)


test_that("{shinytest2} recording: cubic", {
  app <- AppDriver$new(test_path("../.."), name = "cubic", height = 558, width = 735)
  app$click("go")
  app$expect_values()
  app$set_inputs(xmin = -4)
  app$set_inputs(xmin = -3)
  app$expect_values()
  app$set_inputs(xmax = 4)
  app$set_inputs(xmax = 3)
  app$expect_values()
  app$set_inputs(expr = "x^3")
  app$set_inputs(expr = "x^3 ")
  app$set_inputs(expr = "x^3 +")
  app$set_inputs(expr = "x^3 + 2")
  app$set_inputs(expr = "x^3 + 2x")
  app$set_inputs(expr = "x^3 + 2x^")
  app$set_inputs(expr = "x^3 + 2x^2")
  app$set_inputs(expr = "x^3 + 2x^2 ")
  app$set_inputs(expr = "x^3 + 2x^2 -")
  app$set_inputs(expr = "x^3 + 2x^2 - 10")
  app$set_inputs(expr = "x^3 + 2x^2 - 10x")
  app$set_inputs(expr = "x^3 + 2x^2 - 10x ")
  app$set_inputs(expr = "x^3 + 2x^2 - 10x +")
  app$set_inputs(expr = "x^3 + 2x^2 - 10x + ")
  app$set_inputs(expr = "x^3 + 2x^2 - 10x + 2")
  app$set_inputs(expr = "x^3 + 2x^2 - 10x + 29")
  app$click("go")
  app$expect_values()
})
