on:
  pull_request:
    types: [closed]
    branches: [master]

name: Deploy to Posit Connect Cloud

jobs:
  deploy-app:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: posit-dev/actions/publish@v1
        with:
          server-url: https://connect.posit.cloud
          api-key: ${{ secrets.POSIT_CLOUD_API_KEY }}
          config-file: .posit/publish/funcplots-OVPO.toml
          account: victorordu
