name: Funcplots App Tests
run-name: Running Tests on the App
on: [push]
jobs:
  Test-Shiny-App:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
      - run: Rscript -e "print('This is a test for setting up R')"
      
      - uses: r-lib/actions/setup-renv@v2
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: 2
          install-pandoc: false
          