name: Funcplots App Tests
run-name: Running Tests on the App
on: [push]
jobs:
  Test-Shiny-App:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v4
        with:
          r-version: release
      - run: Rscript -e "print('This is a test for setting up R')"
      # - name: Test the app functions
        # uses: actions/checkout@v5
      # - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # - run: Rscript -e ""